

POST http://localhost:3000/clientes
Content-Type: application/json

{
    "nome": "Teste 2",
    "cpf": "14699488773"
}


###
GET http://localhost:3000/clientes/14699488773


###
GET http://localhost:3000/clientes


###
DELETE http://localhost:3000/clientes/2